
train : '/finaldatasetalt2/train/'  
validate : '/finaldatasetalt2/validate/'  
test : '/finaldatasetalt2/test/'  

batch_size: 32
epochs: 10
num_workers: 4
repeat: 4
learning_rate: 0.001
window_size: 1024
stride: 512