mode: "simulation" # simulation | recorded
train : 'data/train/'  
validate : 'data/validate/'  
test : 'data/test/'  
# recorded: 'recording/recording.wav'
model: "mlp"  #  mlp | lstm | cnn1d | cnn2d
#mlp, lstm, cnn1d uses GCC PHAT as input
#cnn2d uses STFT as input
#Suggestions:
# 1. mlp: BCELoss, learning_rate: 0.001, weight_decay: 0, scheduler: 1
# 2. lstm: BCELoss, learning_rate: 0.001, weight_decay: 0, scheduler: None
# 3. cnn1d: CrossEntropyLoss, learning_rate: 0.001, weight_decay: 0, scheduler: None
# 4. cnn2d: CrossEntropyLoss, learning_rate: 0.001, weight_decay: 0, scheduler: None

dataloader: 
  batch_size: 32
  num_workers: 0  
  window_size: 1024
  stride: 512


module:
  loss: "BCELoss" # BCELoss | CrossEntropyLoss | MSELoss | FocalLoss
  learning_rate: 0.001  
  weight_decay: 0.001 
  scheduler:  None 

trainer: 
  epochs: 100
  early_stopping:
    patience: 10
    monitor: "val_loss" # val_loss | val_accuracy
  checkpoint:
    monitor: "val_accuracy" # val_loss | val_accuracy
    mode: "max" # min | max

checkpoint_path: 'Checkpoint/weights=epoch=21-val_loss=0.28-val_accuracy=0.81.ckpt'