nn_model: mlp # mlp | cnn | rnn
loss_function: BCELoss # BCELoss | MSELoss


train_dataset_dir: '/dataset/train/'
val_dataset_dir: '/dataset/validate/'
test_dataset_dir: '/dataset/test/'
batch_size: 32
n_epochs: 5
num_workers: 4